### ISSUE TITLE
velocity dispersion correction

### ISSUE THREAD

**Issue by jpinedaf** [kristina-monsch/ammonia_project#31]
we need to correct for the channel width, just check Friesen et al. (2009, http://iopscience.iop.org/article/10.1088/0004-637X/697/2/1457/pdf) appendix B

This is needed to make the velocity dispersion map figures and analysis

**Comment by jpinedaf** [comment]
notice that the quoted channel width is the FWHM, and it needs to be converted to sigma

**Comment by jpinedaf** [comment]
https://github.com/kristina-monsch/ammonia_project/blob/second_pc/cluster_plots.py#L115 
looks ok except for the missing conversion between FWHM into sigma of the channel width

**Comment by kristina-monsch** [comment]
implemented the correction + the conversion factor: https://github.com/kristina-monsch/ammonia_project/blob/master/linefit_plotting.py#L125 .. it is still giving me an error message which is why it's commented out. It says that the dimensions of both quantities can not be subtracted (i think it's because the channel width does not have a unit, but when I set one, it says that they can not be converted into each other)..I'll look more into this but I bet that it's not hard to solve

**Comment by kristina-monsch** [comment]
checked the linewidth from the parameter maps...
The median of both distributions is 0.4168 km/s (uncorrected) and 0.3955 km/s (corrected)
See the ipython notebook https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/linewidth_check.ipynb for more plots.

![hist_linewidth_comparison](https://cloud.githubusercontent.com/assets/18168392/22063714/99e1e18e-dd80-11e6-9df7-927bee7a2185.png)
![kde_comparison](https://cloud.githubusercontent.com/assets/18168392/22063715/99e4f3ce-dd80-11e6-83d8-a6d745a27605.png)

**Comment by jpinedaf** [comment]
it looks good, except that when plotting you swapped the corrected and uncorrected labels :-)

**Comment by kristina-monsch** [comment]
You're right, thank you!! Here are the updated plots :-)

![hist_linewidth_comparison](https://cloud.githubusercontent.com/assets/18168392/22066594/ec47fb4a-dd8d-11e6-9b74-8ee111c531e9.png)
![kde_comparison](https://cloud.githubusercontent.com/assets/18168392/22066593/ec47ed80-dd8d-11e6-839f-eee5943d08f5.png)

**Comment by kristina-monsch** [comment]
Jaime, could it be that the fit for the peak_snr of 1 is rubbish? I just realised that I plotted the histograms for the line width check for peak_snr=20 and when I changed it to 1, the histograms were really messed up. It looks like the linewidth ranges from 0.04 to 114985292369.0 km/s.....What do you think? Maybe this is the reason, why the "improved" integrated intensity map looks strange, since we need to load in the fit for running it.
I remade the histograms for peak_snr=1, and since the very high linewidths are outliers, I cut them out from the fit. The histograms look completely different now... :-( See this notebook: https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/linewidth_snr1.ipynb
Could it be possible, that due to the low peak_snr we have lots of pixels that can only be poorly fit which results in the drastic range of the linewidth? Shouldn't we be able to correct for this?

**Comment by kristina-monsch** [comment]
Correction in implemented correctly into the code...now make sure to mask the data properly (i.e. cut out all the pixels with unreasonable fits), which will also improve these histograms.

**Comment by kristina-monsch** [comment]
Check https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/linewidth_snr1.ipynb to see the histograms of the masked data. The histograms look more reasonable now, and it seems that the linewidth was extremely noisy in the very low regions....applying the correction to the linewidth got rid of most of these pixels, since they were than flagged out. 
Check also https://github.com/kristina-monsch/ammonia_project/blob/update_moment0_map/fitted_parameters_histograms.ipynb for the ranges of all the other parameters...

--CLOSED--

**Comment by kristina-monsch** [comment]
These plots show the distribution of the fitted parameters after masking them:
![hist_dv](https://cloud.githubusercontent.com/assets/18168392/22253961/9f228cac-e253-11e6-9010-81c7af93a93a.png)
![hist_nnh3](https://cloud.githubusercontent.com/assets/18168392/22253962/9f245e10-e253-11e6-81c9-d1515ee3131f.png)
![hist_tex](https://cloud.githubusercontent.com/assets/18168392/22253963/9f25ad7e-e253-11e6-9892-abfccaab313c.png)
![hist_tk](https://cloud.githubusercontent.com/assets/18168392/22253965/9f2b7f2e-e253-11e6-8ffd-743b36a3fa1c.png)
![hist_vc](https://cloud.githubusercontent.com/assets/18168392/22253964/9f28e746-e253-11e6-829e-a47ca81cdc6e.png)

For the unmasked histograms, see the ipython notebook I've posted earlier.

**Comment by kristina-monsch** [comment]
the velocity correction is implemented and therefore this issue can be closed.
