### ISSUE TITLE
calculate temperature only if using NH3 (1,1) and (2,2)

### ISSUE THREAD

**Issue by jpinedaf** [kristina-monsch/ammonia_project#9]
at this point we will only fit NH3(1,1) and keep Tkin fixed... modify this 
https://github.com/kristina-monsch/ammonia_project/blob/improved_plot/coldammonia_fit.py#L118

We will later use NH3(2.2) to get the Tkin... but for the moment we will only use NH3(1,1)

**Comment by kristina-monsch** [comment]
#10 : keep Tkin=12 K fixed now

```python
        pcube.fiteach(fittype='cold_ammonia', guesses=guesses,
                      use_nearest_as_guess=True, errmap=errmap,
                      integral=False, verbose_level=3,
                      fixed=[T,F,F,F,F,T], signal_cut=2,
                      limitedmax=[F,F,T,F,T,T],
                      limitedmin=[T,T,T,T,T,T],
                      minpars=[5,2.8,12.0,0.04,vmin,0],
                      maxpars=[0,0,17.0,0,vmax,1],
                      position_order = 1/peaksnr, maskmap=planemask,
                      multicore=2)
```

**Comment by jpinedaf** [comment]
looks good 👍

**Comment by kristina-monsch** [comment]
Modified the code a little bit in preparation for adding the (2,2) line. See linefit_include22.ipynb  (#13). But I still need the file and test if it's really working!

**Comment by kristina-monsch** [comment]
- [ ] add the conversion between Jy/beam and K 
- [ ] refactor the code and get more structure in
- [ ] check the results for plausibility ] 
- [ ] try to determine how important the continuum level is; what is the proper value (in units of sigma)?; in which way should the Orion BN/KL be "filtered" out from the analysis (generously cut it out or just exclude certain pixels?) 
- [ ] continuously reduce the SNR and rerun the code

**Comment by kristina-monsch** [comment]
our VLA data has been combined with data from the GBT, which improved the quality a lot. Also the (2,2) line is now included, see 
https://github.com/kristina-monsch/ammonia_project/blob/second_pc/linefit_GBT_11only.ipynb and https://github.com/kristina-monsch/ammonia_project/blob/second_pc/linefit_VLA_GBT.ipynb .

Since the input data requires big memory, I have to run the code on a cluster, see https://github.com/kristina-monsch/ammonia_project/blob/second_pc/linefit_cluster_withoutplots.py .

**Comment by kristina-monsch** [comment]
now: check the results! The (1,1) fit looks quite nice, but I am not sure about the (2,2) fit. But I think we've discussed that the satellite components will only be poorly visible, right @jpinedaf ?

- the kinetic temperature is actually quite high in some pixels, sometimes even ~170 K. Is this reasonable?
- can the fit for both lines be plotted in one spectrum?

**Comment by jpinedaf** [comment]
this is good... make sure the temperature is OK in regions with good line detections. then close

**Comment by kristina-monsch** [comment]
please check the new plots (snr=1) @jpinedaf :
https://github.com/kristina-monsch/ammonia_project/blob/master/plots/VLA_GBT/snr1/snr1_Tex.png and https://github.com/kristina-monsch/ammonia_project/blob/master/plots/VLA_GBT/snr1/snr1_Tkin.png . It looks like in many pixels no temperature could be fitted. I checked the spectra for the empty regions: https://github.com/kristina-monsch/ammonia_project/tree/master/plots/VLA_GBT/spectra_11_22/fitted_spectra/clarify_Tkin (sorry that you can't see the position on the data cube but I tried to follow the empty parts from the Tkin plot..)

I am not sure what exactly is going wrong, but it looks like that the kinetic temperature can not be fitted in many pixels. But this does not necessarily mean, that the (2,2) line is not well resolved (because then Tkin could be simply off by some order of magnitudes, right?)
Also in regions where the line detections are good, we get this crazy behavior of the temperatures...
